apiVersion: apps/v1
kind: Deployment
metadata:
  name: quillser-deployment
spec:
  selector:
    matchLabels:
      app: quillser
  replicas: 1
  template:
    metadata:
      labels:
        app: quillser
    spec:
      containers:
      - name: quillser-api
        image: shameelfazul/quillser:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Host
            value: mongodb-service 
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: quillser-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: quillser-service
spec:
  type: LoadBalancer
  selector:
    app: quillser
  ports:
    - port: 80
      targetPort: 80

